### ISSUE TITLE
stuck in the joining world section

### ISSUE THREAD

**Issue by Canbinlol** [benbenlaw/skyopolis-5#22]
Tested in both b5.1 and 1.0 version of the pack, java version 17.0.3.1. CPU, GPU, RAM spares a lot.
![图像_2022-07-18_152246447](https://user-images.githubusercontent.com/91358346/179462384-afda6cab-b342-4544-9565-1a3750a0cb95.png)
(the screenshot is taken in version b5.1)
It seems that I have entered the world but stuck in the progress of entering another dimension. I know it is probably not an issue of the pack.  But  I do want to play the pack, so do you know how to fix that? Thanks.

**Comment by benbenlaw** [comment]
post logs as well

**Comment by Canbinlol** [comment]
[latest.log](https://github.com/benbenlaw/skyopolis-5/files/9130184/latest.log)
Some of the log is in Chinese but should not affect reading.

**Comment by benbenlaw** [comment]
single player?

**Comment by Canbinlol** [comment]
Yes.

**Comment by Canbinlol** [comment]
[latest.log](https://github.com/benbenlaw/skyopolis-5/files/9130216/latest.log)
I reinstalled the pack and did the same thing again, this is a cleaner version that I didn't change or add any other thing other than the original v1.0 pack.

**Comment by 10935336** [comment]
In my use case this was caused by Extra Storage  https://github.com/Edivad99/ExtraStorage/issues/59
For player, just set `versionCheck = false` in `\minecraft\config\fml.toml`.
For package makers, upgrading to ExtraStorage-1.18.2-2.2.0 should fix the problem.

This is presumably due to a poor connection to Github. So you can see that often Chinese players are reporting this issue because Github is blocked in mainland China.

Thanks to OPCN for helping to solve this problem.

**Comment by Gurkysword12** [comment]
Fixed already
